# Generated by Django 3.2.13 on 2022-06-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('short_url', models.BigAutoField(primary_key=True, serialize=False)),
                ('original_url', models.URLField(max_length=1024, unique=True)),
            ],
        ),
    ]
